[package]
name = "qpsk_modulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
bitvec = "1.0.1"
csv = "1.2.1"
env_logger = "0.10.0"
log = "0.4.17"
